mautic.db:
  container_name: mautic.db
  hostname: mautic-db
  #restart: always
  image: mysql:5.6
  volumes:
   - ../volumes/db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: M@ut1c


mautic.app:
  container_name: mautic.app
  hostname: mautic.app
  #restart: always
  image: mautic:2.0.1dev
  volumes:
   - ../volumes/nginx/mautic.conf:/etc/nginx/conf.d/default.conf
   - ../volumes/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
   - ../volumes/cron/mautic:/etc/cron.d/mautic
  links:
    - mautic.db:db
  ports:
    - 80:80
